permalink:           pretty

# Setup
title:               'PyTorch Deep Learning Minicourse'
tagline:             'Gotta learn them all'
url:                 https://atcold.github.io/pytorch-Deep-Learning-Minicourse/
baseurl:             '/pytorch-Deep-Learning-Minicourse'

# About/contact
author:
name:                atcold
url:                 https://twitter.com/alfcnz
github:
  repo:              https://github.com/atcold/pytorch-Deep-Learning-Minicourse/

# Custom vars
version:             dlsp20

multilingual:        false
src:                 "."
default_theme:       "ayu"

# For Maths
markdown:            kramdown

# To use hljs, disable the default highlighter
kramdown:
  syntax_highlighter_opts:
    disable : true


# Chapter Configuration (up to a 2 level nested list)

chapters:
  - path: chapters/01.md
    sections:
      - path: chapters/01-1.md
      - path: chapters/01-2.md
      - path: chapters/01-3.md
  - path: chapters/02.md

