permalink:           pretty

# Setup
title:               'Deep Learning'
url:                 https://atcold.github.io/pytorch-Deep-Learning/
baseurl:             '/pytorch-Deep-Learning'
homepage_title:      Home
default_lang:        'en'

# About/contact
author:
name:                atcold
url:                 https://twitter.com/alfcnz
github:
  repo:              https://github.com/atcold/pytorch-Deep-Learning/

# Custom vars
version:             dlsp20

src:                 "."
default_theme:       "ayu"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "custom"

# For Maths
markdown:            kramdown

# To use hljs, disable the default highlighter
kramdown:
  syntax_highlighter_opts:
    disable: true
  math_engine: null

exclude:
  - jekyllbook
  - en/index.md
  - vendor

################################### English ####################################
prologues:
  - path: en/about.md
chapters:
  - path: en/week01/01.md
    sections:
      - path: en/week01/01-1.md
      - path: en/week01/01-2.md
      - path: en/week01/01-3.md
  - path: en/week02/02.md
    sections:
      - path: en/week02/02-1.md
      - path: en/week02/02-2.md
      - path: en/week02/02-3.md
  - path: en/week03/03.md
    sections:
      - path: en/week03/03-1.md
      - path: en/week03/03-2.md
      - path: en/week03/03-3.md
  - path: en/week04/04.md
    sections:
      - path: en/week04/04-1.md
  - path: en/week05/05.md
    sections:
      - path: en/week05/05-1.md
      - path: en/week05/05-2.md
      - path: en/week05/05-3.md
  - path: en/week06/06.md
    sections:
      - path: en/week06/06-1.md
      - path: en/week06/06-2.md
      - path: en/week06/06-3.md
  - path: en/week07/07.md
    sections:
      - path: en/week07/07-1.md
      - path: en/week07/07-2.md
      - path: en/week07/07-3.md
  - path: en/week08/08.md
    sections:
      - path: en/week08/08-1.md
      - path: en/week08/08-2.md
      - path: en/week08/08-3.md
  - path: en/week09/09.md
    sections:
      - path: en/week09/09-1.md
      - path: en/week09/09-2.md
      - path: en/week09/09-3.md
  - path: en/week10/10.md
    sections:
      - path: en/week10/10-1.md
      - path: en/week10/10-2.md
      - path: en/week10/10-3.md
  - path: en/week11/11.md
    sections:
      - path: en/week11/11-1.md
      - path: en/week11/11-2.md
      - path: en/week11/11-3.md
  - path: en/week12/12.md
    sections:
      - path: en/week12/12-1.md
      - path: en/week12/12-2.md
      - path: en/week12/12-3.md
  - path: en/week13/13.md
    sections:
      - path: en/week13/13-1.md
      - path: en/week13/13-2.md
      - path: en/week13/13-3.md
  - path: en/week14/14.md
    sections:
      - path: en/week14/14-1.md
      - path: en/week14/14-2.md
      - path: en/week14/14-3.md
#epilogues:
#  - path: chapters/end.md

################################### Mandarin ###################################
zh:
  title: '深度学习'
  prologues:
    - path: zh/about.md
  chapters:
    - path: zh/week01/01.md
      sections:
        - path: zh/week01/01-1.md
        - path: zh/week01/01-2.md
        - path: zh/week01/01-3.md
    - path: zh/week02/02.md
      sections:
        - path: zh/week02/02-1.md
        - path: zh/week02/02-2.md
        - path: zh/week02/02-3.md
    - path: zh/week03/03.md
      sections:
        - path: zh/week03/03-1.md
        - path: zh/week03/03-2.md
        - path: zh/week03/03-3.md
    - path: zh/week04/04.md
      sections:
        - path: zh/week04/04-1.md
    - path: zh/week05/05.md
      sections:
        - path: zh/week05/05-1.md
        - path: zh/week05/05-2.md
        - path: zh/week05/05-3.md
    - path: zh/week06/06.md
      sections:
        - path: zh/week06/06-2.md
        - path: zh/week06/06-3.md
    - path: zh/week07/07.md
      sections:
        - path: zh/week07/07-1.md
        - path: zh/week07/07-2.md
        - path: zh/week07/07-3.md
    - path: zh/week08/08.md
      sections:
        - path: zh/week08/08-1.md
        - path: zh/week08/08-2.md
        - path: zh/week08/08-3.md
    - path: zh/week09/09.md
      sections:
        - path: zh/week09/09-1.md
        - path: zh/week09/09-2.md
        - path: zh/week09/09-3.md
    - path: zh/week10/10.md
      sections:
        - path: zh/week10/10-1.md
        - path: zh/week10/10-2.md
        - path: zh/week10/10-3.md
    - path: zh/week11/11.md
      sections:
        - path: zh/week11/11-1.md
        - path: zh/week11/11-2.md
        - path: zh/week11/11-3.md
    - path: zh/week12/12.md
      sections:
        - path: zh/week12/12-1.md
        - path: zh/week12/12-2.md
        - path: zh/week12/12-3.md
    - path: zh/week13/13.md
      sections:
        - path: zh/week13/13-1.md
        - path: zh/week13/13-2.md
        - path: zh/week13/13-3.md
    - path: zh/week14/14.md
      sections:
        - path: zh/week14/14-1.md

#################################### Korean ####################################
ko:
  title: '딥러닝'
  chapters:
    - path: ko/week01/01.md
      sections:
        - path: ko/week01/01-1.md
        - path: ko/week01/01-2.md
        - path: ko/week01/01-3.md
    - path: ko/week02/02.md
      sections:
        - path: ko/week02/02-1.md
        - path: ko/week02/02-2.md
        - path: ko/week02/02-3.md
    - path: ko/week03/03.md
      sections:
        - path: ko/week03/03-1.md
        - path: ko/week03/03-2.md
        - path: ko/week03/03-3.md
    - path: ko/week04/04.md
      sections:
        - path: ko/week04/04-1.md
    - path: ko/week05/05.md
      sections:
        - path: ko/week05/05-1.md
        - path: ko/week05/05-2.md
        - path: ko/week05/05-3.md
    - path: ko/week06/06.md
      sections:
        - path: ko/week06/06-1.md
        - path: ko/week06/06-2.md
        - path: ko/week06/06-3.md
    - path: ko/week07/07.md
      sections:
        - path: ko/week07/07-1.md
        - path: ko/week07/07-2.md
    - path: ko/week08/08.md
      sections:
        - path: ko/week08/08-1.md
        - path: ko/week08/08-2.md
        - path: ko/week08/08-3.md
    - path: ko/week09/09.md
      sections:
        - path: ko/week09/09-1.md
        - path: ko/week09/09-2.md
        - path: ko/week09/09-3.md
    - path: ko/week10/10.md
      sections:
        - path: ko/week10/10-1.md
    - path: ko/week11/11.md
      sections:
        - path: ko/week11/11-1.md
    - path: ko/week12/12.md
      sections:
        - path: ko/week12/12-1.md
        - path: ko/week12/12-2.md
        - path: ko/week12/12-3.md
    - path: ko/week13/13.md
      sections:
    - path: ko/week14/14.md
      sections:
        - path: ko/week14/14-1.md
        - path: ko/week14/14-2.md
        - path: ko/week14/14-3.md

################################### Spanish ####################################
es:
  title:   'Aprendizaje Profundo'
  chapters:
    - path: es/week01/01.md
      sections:
        - path: es/week01/01-1.md
        - path: es/week01/01-2.md
        - path: es/week01/01-3.md
    - path: es/week02/02.md
      sections:
        - path: es/week02/02-1.md
        - path: es/week02/02-2.md
        - path: es/week02/02-3.md
    - path: es/week03/03.md
      sections:
        - path: es/week03/03-1.md
        - path: es/week03/03-2.md
        - path: es/week03/03-3.md
    - path: es/week04/04.md
      sections:
        - path: es/week04/04-1.md
    - path: es/week05/05.md
      sections:
        - path: es/week05/05-1.md
        - path: es/week05/05-2.md
        - path: es/week05/05-3.md
    - path: es/week06/06.md
      sections:
        - path: es/week06/06-1.md
        - path: es/week06/06-2.md
        - path: es/week06/06-3.md
    - path: es/week07/07.md
      sections:
        - path: es/week07/07-1.md
        - path: es/week07/07-2.md
        - path: es/week07/07-3.md
    - path: es/week08/08.md
      sections:
        - path: es/week08/08-1.md
        - path: es/week08/08-2.md
        - path: es/week08/08-3.md
    - path: es/week09/09.md
      sections:
        - path: es/week09/09-1.md
        - path: es/week09/09-2.md
        - path: es/week09/09-3.md
    - path: es/week10/10.md
      sections:
        - path: es/week10/10-1.md
        - path: es/week10/10-2.md
        - path: es/week10/10-3.md
    - path: es/week11/11.md
      sections:
        - path: es/week11/11-1.md
        - path: es/week11/11-2.md
        - path: es/week11/11-3.md
    - path: es/week12/12.md
      sections:
        - path: es/week12/12-1.md
        - path: es/week12/12-2.md
        - path: es/week12/12-3.md
    - path: es/week13/13.md
      sections:
        - path: es/week13/13-1.md
        - path: es/week13/13-2.md
        - path: es/week13/13-3.md
    - path: es/week14/14.md
      sections:
        - path: es/week14/14-1.md
        - path: es/week14/14-2.md
        - path: es/week14/14-3.md

################################### Italian ####################################
it:
  title: 'Apprendimento Profondo'
  chapters:
    - path: it/week01/01.md
      sections:
        - path: it/week01/01-1.md
        - path: it/week01/01-2.md
        - path: it/week01/01-3.md
    - path: it/week02/02.md
      sections:
        - path: it/week02/02-1.md
        - path: it/week02/02-2.md
        - path: it/week02/02-3.md
    - path: it/week03/03.md
      sections:
        - path: it/week03/03-1.md
        - path: it/week03/03-2.md
        - path: it/week03/03-3.md
    - path: it/week04/04.md
      sections:
        - path: it/week04/04-1.md
    - path: it/week05/05.md
      sections:
        - path: it/week05/05-1.md
        - path: it/week05/05-2.md
        - path: it/week05/05-3.md
    - path: it/week06/06.md
      sections:
        - path: it/week06/06-1.md
        - path: it/week06/06-2.md
        - path: it/week06/06-3.md
    - path: it/week07/07.md
      sections:
        - path: it/week07/07-1.md
        - path: it/week07/07-2.md
        - path: it/week07/07-3.md
    - path: it/week08/08.md
      sections:
        - path: it/week08/08-1.md
        - path: it/week08/08-2.md
        - path: it/week08/08-3.md
    - path: it/week09/09.md
      sections:
        - path: it/week09/09-1.md
        - path: it/week09/09-2.md
        - path: it/week09/09-3.md
    - path: it/week10/10.md
      sections:
        - path: it/week10/10-1.md
        - path: it/week10/10-2.md
        - path: it/week10/10-3.md
    - path: it/week11/11.md
      sections:
        - path: it/week11/11-1.md
        - path: it/week11/11-2.md
        - path: it/week11/11-3.md

################################### Turkish ####################################
tr:
  title: 'Derin Öğrenme'
  chapters:
    - path: tr/week01/01.md
      sections:
        - path: tr/week01/01-1.md
        - path: tr/week01/01-2.md
    - path: tr/week02/02.md
      sections:
        - path: tr/week02/02-1.md
    - path: tr/week03/03.md
      sections:
        - path: tr/week03/03-1.md
        - path: tr/week03/03-2.md
    - path: tr/week04/04.md
      sections:
        - path: tr/week04/04-1.md
    - path: tr/week05/05.md
      sections:
        - path: tr/week05/05-1.md
        - path: tr/week05/05-2.md
        - path: tr/week05/05-3.md
    - path: tr/week06/06.md
      sections:
        - path: tr/week06/06-1.md
        - path: tr/week06/06-3.md
    - path: tr/week07/07.md
      sections:
        - path: tr/week07/07-1.md
        - path: tr/week07/07-2.md
        - path: tr/week07/07-3.md
    - path: tr/week08/08.md
      sections:
        - path: tr/week08/08-1.md
        - path: tr/week08/08-2.md
        - path: tr/week08/08-3.md
        - path: tr/week09/09-1.md
        - path: tr/week09/09-2.md
        - path: tr/week09/09-3.md
    - path: tr/week10/10.md
      sections:
        - path: tr/week10/10-1.md
        - path: tr/week10/10-3.md
    - path: tr/week11/11.md
      sections:
        - path: tr/week11/11-1.md
        - path: tr/week11/11-2.md
        - path: tr/week11/11-3.md
    - path: tr/week12/12.md
      sections:
        - path: tr/week12/12-1.md
        - path: tr/week12/12-3.md
    - path: tr/week13/13.md
      sections:
        - path: tr/week13/13-3.md
    - path: tr/week14/14.md
      sections:
        - path: tr/week14/14-1.md
        - path: tr/week14/14-2.md

################################## Japanese ####################################
ja:
  title: '深層学習'
  chapters:
    - path: ja/week01/01.md
      sections:
        - path: ja/week01/01-1.md
    - path: ja/week03/03.md
      sections:
        - path: ja/week03/03-1.md
    - path: ja/week07/07.md
      sections:
        - path: ja/week07/07-1.md
        - path: ja/week07/07-2.md
        - path: ja/week07/07-3.md

#################################### Arabic #####################################
ar:
  title: 'التعلم العميق'
  chapters:
    - path: ar/week01/01.md
      sections:
        - path: ar/week01/01-1.md
        - path: ar/week01/01-2.md
        - path: ar/week01/01-3.md
    - path: ar/week02/02.md
    - path: ar/week03/03.md
      sections:
        - path: ar/week03/03-2.md
        - path: ar/week03/03-3.md
    - path: ar/week04/04.md
      sections:
        - path: ar/week04/04-1.md
    - path: ar/week05/05.md
      sections:
        - path: ar/week05/05-1.md
        - path: ar/week05/05-2.md
        - path: ar/week05/05-3.md
    - path: ar/week06/06.md
      sections:
        - path: ar/week06/06-1.md
        - path: ar/week06/06-2.md
        - path: ar/week06/06-3.md
    - path: ar/week07/07.md
      sections:
        - path: ar/week07/07-2.md
        - path: ar/week07/07-3.md
    - path: ar/week07/08.md
    - path: ar/week11/11.md
    - path: ar/week12/12.md
    - path: ar/week13/13.md
      sections:
        - path: ar/week13/13-1.md
        - path: ar/week13/13-3.md
    - path: ar/week14/14.md
      sections:
        - path: ar/week14/14-2.md

#################################### French ####################################
fr:
  title: 'Apprentissage profond'
  chapters:
    - path: fr/week01/01.md
      sections:
        - path: fr/week01/01-1.md
        - path: fr/week01/01-2.md
        - path: fr/week01/01-3.md
    - path: fr/week02/02.md
      sections:
        - path: fr/week02/02-1.md
        - path: fr/week02/02-2.md
        - path: fr/week02/02-3.md
    - path: fr/week03/03.md
      sections:
        - path: fr/week03/03-1.md
        - path: fr/week03/03-2.md
        - path: fr/week03/03-3.md
    - path: fr/week04/04.md
      sections:
        - path: fr/week04/04-1.md
    - path: fr/week05/05.md
      sections:
        - path: fr/week05/05-1.md
        - path: fr/week05/05-2.md
        - path: fr/week05/05-3.md
    - path: fr/week06/06.md
      sections:
        - path: fr/week06/06-1.md
        - path: fr/week06/06-2.md
        - path: fr/week06/06-3.md
    - path: fr/week07/07.md
      sections:
        - path: fr/week07/07-1.md
        - path: fr/week07/07-2.md
        - path: fr/week07/07-3.md
    - path: fr/week08/08.md
      sections:
        - path: fr/week08/08-1.md
        - path: fr/week08/08-2.md
        - path: fr/week08/08-3.md
    - path: fr/week09/09.md
      sections:
        - path: fr/week09/09-1.md
        - path: fr/week09/09-2.md
        - path: fr/week09/09-3.md
    - path: fr/week10/10.md
      sections:
        - path: fr/week10/10-1.md
        - path: fr/week10/10-2.md
        - path: fr/week10/10-3.md
    - path: fr/week11/11.md
      sections:
        - path: fr/week11/11-1.md
        - path: fr/week11/11-2.md
        - path: fr/week11/11-3.md
    - path: fr/week12/12.md
      sections:
        - path: fr/week12/12-1.md
        - path: fr/week12/12-2.md
        - path: fr/week12/12-3.md
    - path: fr/week13/13.md
      sections:
        - path: fr/week13/13-1.md
        - path: fr/week13/13-2.md
        - path: fr/week13/13-3.md
    - path: fr/week14/14.md
      sections:
        - path: fr/week14/14-1.md
        - path: fr/week14/14-2.md
        - path: fr/week14/14-3.md

#################################### Farsi #####################################
fa:
  title: 'یادگیری عمیق'
  chapters:
    - path: en/week03/03.md
      sections:
        - path: fa/week03/03-3.md
    - path: fa/week04/04.md
      sections:
        - path: fa/week04/04-1.md
    - path: fa/week06/06.md
      sections:
        - path: fa/week06/06-1.md
        - path: fa/week06/06-2.md
    - path: fa/week09/09.md
    - path: fa/week12/12.md
      sections:
        - path: fa/week09/09-1.md
    - path: fa/week13/13.md
      sections:
        - path: fa/week13/13-1.md

#################################### Russian ####################################
ru:
  title: 'Глубокое обучение'
  chapters:
    - path: ru/week01/01.md
      sections:
        - path: ru/week01/01-1.md
        - path: ru/week01/01-2.md
 
################################### Vietnamese ####################################
vn:
  title: 'HỌC SÂU'
chapters:
  - path: vi/Tuần 01/01.md
    sections:
      - path: vi/Tuần 01/01-1.md
      - path: vi/Tuần 01/01-2.md
      - path: vi/Tuần 01/01-3.md
