permalink:           pretty

# Setup
title:               'Deep Learning'
tagline:             'Gotta learn them all'
url:                 https://atcold.github.io/pytorch-Deep-Learning/
baseurl:             '/pytorch-Deep-Learning'
homepage_title:      Home
default_lang:        'en'

# About/contact
author:
name:                atcold
url:                 https://twitter.com/alfcnz
github:
  repo:              https://github.com/atcold/pytorch-Deep-Learning/

# Custom vars
version:             dlsp20

src:                 "."
default_theme:       "ayu"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "withmacros"

# For Maths
markdown:            kramdown

# To use hljs, disable the default highlighter
kramdown:
  syntax_highlighter_opts:
    disable : true

exclude:
  - jekyllbook

# Chapter Configuration (up to a 2 level nested list)

prologues:
  - path: chapters/about.md
chapters:
  - path: chapters/01.md
    sections:
      - path: chapters/01-1.md
      - path: chapters/01-2.md
      - path: chapters/01-3.md
  - path: chapters/02.md
    sections:
      - path: chapters/02-1.md
      - path: chapters/02-2.md
      - path: chapters/02-3.md
  - path: chapters/03.md
    sections:
      - path: chapters/03-1.md
      - path: chapters/03-2.md
      - path: chapters/03-3.md
  - path: chapters/04.md
    sections:
      - path: chapters/04-1.md
#epilogues:
#  - path: chapters/end.md

# The only required component of multiple languages is
# a `zh.md` for the index, or `zh/index.md`.
# The only supported config so far is "title" and "tagline"
zh:
  title:   '深度学习'
  tagline: 'Gotta learn them all in 中文'
  prologues:
    - path: zh/about.md
  chapters:
    - path: zh/01.md
      sections:
        - path: zh/01-1.md
        - path: zh/01-2.md
        - path: zh/01-3.md
    - path: zh/02.md
      sections:
        - path: zh/02-1.md
        - path: zh/02-2.md
        - path: zh/02-3.md
